### ISSUE TITLE
Date issue psycopg2.errors.DatetimeFieldOverflow: date/time field value out of range: "1629097199999"

### ISSUE THREAD

**Issue by visch** [AutoIDM/tap-clickup#54]
Dustin Miller on Meltano's slack reported this to me

Comes from here https://github.com/AutoIDM/tap-clickup/blob/main/tap_clickup/schemas/folder.json#L47

**Comment by visch** [comment]
target-postgres has the issue, looks like others may as well. 

https://github.com/singer-io/getting-started/blob/ca5c56f16e67e0c2da49e9bb94d6f52fb19c9de6/docs/DISCOVERY_MODE.md#schemas points to date-time , which points to https://datatracker.ietf.org/doc/html/rfc3339

So we shouldn't call due-date a date-time format. Should change it to string or int.

Only worried about int because of https://en.wikipedia.org/wiki/Year_2038_problem , maybe it'll be the 64bit kind? Unsure easy fix once we pick int/string though!

**Comment by visch** [comment]
Same problem as #50 after further evaluation!

**Comment by LucasZielke** [comment]
Yeah it seems like Meltano _as a solution_ wants to add record transformations as an additional layer into the mix so like `Tap | Transformation | Target` or replace them with like StreamMaps which will be its own hurdle.

Singers/[singer-python](https://github.com/singer-io/singer-python/) had its own [transformer](https://github.com/singer-io/singer-python/blob/master/singer/transform.py) that was built but it seems like it was scrapped when it moved to singer-sdk. 

If we wanted to have this convert to the proper format inside the tap, it seems like there are really only two clean options: including the singer-python to utilize the transformer, or building a custom plugin for date-time conversions and stream mapping the date-times as `epoch`.

Im probably going to submit a `new feature` to the singer-sdk to put in datetime transformations because the already included a custom md5 hash plugin, but this seems like this could be very relevant

**Comment by visch** [comment]
Wow @LucasZielke  thanks for diving in! 

I agree a transformer would work here, and I wonder about our other options. I try to think about the transformer as something you would use if you really wanted to transform the data from the tap into another target. Generally the ELT and transforming at the target is the best way to go especially for a DW target. Where the transformer makes a ton of sense to me is SaaS targets where you may want to jump over the DW need. 

Here's a few other options

1. Since the value doesn't follow singers recommended date-time format `rfc3339` we could stop saying this is a date-time in the schema, and just say the value is an int. That removes this error, and allows the downstream Datawarehouse to have the data and convert and do as they please! (Very easy to do!) 
2. Run the transform directly in tap-clickup to get the date in rfc3339 format

**Comment by visch** [comment]
Thank you so much for that @LucasZielke  , appreciate it!
